---

- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  
  tasks:

    - name: installing troubleshooting packages
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - htop
        - vim
        - ncdu

    - name: |
        Ensure a job that runs at 04 (08 EST) exists.
        Creates an cron entry "0 4 * * docker system prune --volumes --force"
      cron:
        name: "prune unused docker objects"
        minute: "0"
        hour: "04"
        job: "docker system prune --volumes --force"